# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

{{ if not .Values.existingService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aim-chromadb.release.fullname" . }}
  labels:
    app: {{ include "aim-chromadb.release.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.deployment.ports.http }}
    targetPort: http
  selector:
    app: {{ include "aim-chromadb.release.fullname" . }}
{{- end -}}
