# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image:
  repository: "chromadb/chroma"
  tag: "1.3.5"
  pullPolicy: "IfNotPresent"

existingService: null

nameOverride: null
fullnameOverride: null

deployment:
  ports:
    http: 8000
  args:
    - "run"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8000"
    - "--path"
    - "/chroma/.chroma/index"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

persistence:
  enabled: true
  size: "10Gi"
  # storageClassName: mlstorage

metadata:
  labels: {}
