# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.fullname" . }}
data:
  default_settings.json: |
    { "continue.enableNextEdit": false }
