# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.fullname" . }}
data:
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "src/*" }}
  {{ $key := $path | trimPrefix "src/" }}
  {{- $key }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
